%%{init: {'theme': 'neutral'}}%%
timeline
    Experiment 1 : Feature Engineering<br>One-hot encoding
                 : Model<br>Regularized regression
                 : Hyperparameters<br>Default settings
    Experiment 2 : Feature Engineering<br>Label encodding
                 : Model<br>Random Forest
                 : Hyperparameters<br>Max Depth = 50<br>Max Features = 25
    Experiment 3 : Feature Engineering<br>Embeddings
                 : Model<br>Random Forest
                 : Hyperparameters<br>Max Depth = 30<br>Max Features = 40
    Experiment 4 : Feature Engineering<br>Embeddings
                 : Model<br>Elastic Net Regularized regression
                 : Hyperparameters<br>L1 Ratio = 0.5
    Experiment 5 : Feature Engineering<br>Label encodding
                 : Model<br>XGBoost
                 : Hyperparameters<br>Max Depth = 10<br>Trees = 500<br>Learning Rate = 0.001
