project:
  type: book

book:
  title: "Machine Learning Design for Business"
  author: "Brad Boehmke"
  date: today
  search: true
  repo-url: https://github.com/bradleyboehmke/uc-bana-7085
  repo-branch: main
  repo-actions: [edit, issue]
  downloads: [pdf, epub]
  sharing: [twitter]

  chapters:
    - index.qmd
    - part: "Laying the Foundation"
    - 01-intro-ml-system.qmd
    - 02-before-we-build.qmd
    - part: "DataOps"
    - 03-dataops-role.qmd
    - 04-dataops-build.qmd
    - part: "ModelOps"
    - part: "DevOps"
    - part: "The Human Side of ML Systems"
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    code-link: true
    callout-appearance: simple
    number-depth: 2
    mermaid:
      theme: neutral
  pdf:
    documentclass: scrreprt
    number-depth: 2
