project:
  type: book

book:
  title: "Machine Learning Design for Business"
  author: "Brad Boehmke"
  date: today
  search: true
  sidebar:
    style: docked
  repo-url: https://github.com/bradleyboehmke/uc-bana-7075
  repo-branch: main
  repo-actions: [edit, issue]
  downloads: [epub]
  sharing: [twitter]

  chapters:
    - index.qmd
    - part: "Laying the Foundation"
      chapters:
        - 01-intro-ml-system.qmd
        - 02-before-we-build.qmd
    - part: "DataOps"
      chapters:
        - 03-dataops-role.qmd
        - 04-dataops-build.qmd
    - part: "ModelOps"
      chapters:
        - 05-modelops-role.qmd
        - 06-modelops-experimenting.qmd
        - 07-modelops-versioning.qmd
        - 08-modelops-deployment.qmd
        - 09-modelops-monitoring.qmd
    - part: "DevOps"
      chapters:
        - 10-devops-role.qmd
        - 11-devops-git.qmd
    - part: "Human Elements"
      chapters:
        - 12-human-side-of-ml.qmd
        - 13-continued-learning.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    code-link: true
    callout-appearance: simple
    number-depth: 2
    mermaid:
      theme: neutral
