on:
    push:
      branches: main
    pull_request:
      branches: main
    # to be able to trigger a manual build
    workflow_dispatch:
    schedule:
      # run every day at 11 PM
      - cron: '0 23 * * *'

name: Render and publish book

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          # To install LaTeX to build PDF book
          tinytex: true
          
      - name: Install dependencies
        run: |
          # $CONDA is an environment variable pointing to the root of the miniconda directory
          $CONDA/bin/conda env update --file bana7085.yml --name base
      
      - name: Render and Publish
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
          path: book
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
